### ISSUE TITLE
Can't flag others' posts NSFW

### ISSUE THREAD

**Issue by kindfulkirby** [edave64/souplements#1]
When someone posts a NSFW thing and I want to flag it, because it's not hidden, I can't.

Probably because I have to browse soup in NSFW mode to even use your script?

Would be cool if there was something to be done.

EDIT: Alternatively the filter is just not working and those things were already tagged...

**Comment by kindfulkirby** [comment]
_lol_ Fixed it by going back to safe mode. Either I missed it or the documentation should reflect this ;)

**Comment by edave64** [comment]
This is a normal soup feature. You cannot flag post as NSFW while in NSFW mode. This way, you can only flag posts as NSFW that aren't already flagged.

BetterNSFW should only hide NSFW posts while soup is in SFW mode.
